# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    labels:
      - "dependencies"
    groups:
      babel:
        applies-to: version-updates
        patterns:
          - "@babel/*"
      embroider:
        applies-to: version-updates
        patterns:
          - "@embroider/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "@eslint/*"
          - eslint
          - eslint-*      
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
