// Generated by CoffeeScript 1.4.0
(function() {

  window.App = Ember.Application.create({
    customEvents: {
      blur: 'blur'
    }
  });

  App.ApplicationView = Ember.View.extend({
    classNames: 'ember-app',
    templateName: 'application'
  });

  App.ApplicationController = Ember.Controller.extend({
    tableAjaxExampleController: Ember.computed(function() {
      return Ember.get('App.TableAjaxExample.TableController').create();
    }).property(),
    tableBarExampleController: Ember.computed(function() {
      return Ember.get('App.TableBarExample.TableController').create();
    }).property(),
    tableSparklineExampleController: Ember.computed(function() {
      return Ember.get('App.TableSparklineExample.TableController').create();
    }).property(),
    tableHorizonExampleController: Ember.computed(function() {
      return Ember.get('App.TableHorizonExample.TableController').create();
    }).property(),
    tableSimpleExampleController: Ember.computed(function() {
      return Ember.get('App.TableSimpleExample.TableController').create();
    }).property(),
    tableEditableExampleController: Ember.computed(function() {
      return Ember.get('App.TableEditableExample.TableController').create();
    }).property(),
    treeTableExampleController: Ember.computed(function() {
      var controller;
      controller = Ember.get('App.TreeTableExample.TableController').create();
      controller.set('data', window.treedata);
      return controller;
    }).property()
  });

}).call(this);
