// Generated by CoffeeScript 1.3.3
(function() {

  window.App = Ember.Application.create();

  App.ApplicationView = Ember.View.extend({
    classNames: 'ember-app',
    templateName: 'application'
  });

  App.ApplicationController = Ember.Controller.extend({
    tableBarExampleController: Ember.computed(function() {
      return Ember.get('App.TableBarExample.TableController').create();
    }).property(),
    tableSparklineExampleController: Ember.computed(function() {
      return Ember.get('App.TableSparklineExample.TableController').create();
    }).property(),
    tableHorizonExampleController: Ember.computed(function() {
      return Ember.get('App.TableHorizonExample.TableController').create();
    }).property(),
    tableSimpleExampleController: Ember.computed(function() {
      return Ember.get('App.TableSimpleExample.TableController').create();
    }).property(),
    treeTableExampleController: Ember.computed(function() {
      var controller;
      controller = Ember.get('App.TreeTableExample.TableController').create();
      controller.set('data', window.treedata);
      return controller;
    }).property()
  });

  App.Router = Ember.Router.extend({
    root: Ember.Route.extend({
      index: Ember.Route.extend({
        route: '/'
      })
    })
  });

  App.initialize();

}).call(this);
