export default [{
   patient:"Alice",
   patientAge:65,
   visits:1,
   date:"1/7/14",
   time:"9:30 AM",
   unit:"preop",
   physician:"Adams",
   charge:0,
   copay:"0",
   insurance:"Aetna PPO",
   inpatient:"TRUE"
}, {
   patient:"Alice",
   patientAge:65,
   visits:1,
   date:"1/7/14",
   time:"10:30 AM",
   unit:"operating room",
   physician:"Adams",
   charge:1200,
   copay:"0",
   insurance:"Aetna PPO",
   inpatient:"TRUE"
}, {
   patient:"Alice",
   patientAge:65,
   visits:1,
   date:"1/7/14",
   time:"12:15 PM",
   unit:"ICU",
   physician:"Adams",
   charge:0,
   copay:"0",
   insurance:"Aetna PPO",
   inpatient:"TRUE"
}, {
   patient:"Alice",
   patientAge:65,
   visits:1,
   date:"1/7/14",
   time:"6:00 PM",
   unit:"recovery",
   physician:"Adams",
   charge:600,
   copay:"0",
   insurance:"Aetna PPO",
   inpatient:"TRUE"
}, {
   patient:"Alice",
   patientAge:65,
   visits:1,
   date:"1/8/14",
   time:"11:00 AM",
   unit:"discharge",
   physician:"Adams",
   charge:0,
   copay:"0",
   insurance:"Aetna PPO",
   inpatient:"TRUE"
}, {
   patient:"Alice",
   patientAge:65,
   visits:2,
   date:"1/13/14",
   time:"2:00 PM",
   unit:"office",
   physician:"Adams",
   charge:120,
   copay:"25",
   insurance:"Aetna PPO",
   inpatient:"FALSE"
}, {
   patient:"Alice",
   patientAge:65,
   visits:3,
   date:"2/25/14",
   time:"1:00 PM",
   unit:"office",
   physician:"Baker",
   charge:150,
   copay:"25",
   insurance:"Aetna PPO",
   inpatient:"FALSE"
}, {
   patient:"Alice",
   patientAge:65,
   visits:4,
   date:"3/25/14",
   time:"1:00 PM",
   unit:"office",
   physician:"Baker",
   charge:150,
   copay:"25",
   insurance:"Aetna PPO;Medicare",
   inpatient:"FALSE"
}, {
   patient:"Bob",
   patientAge:82,
   visits:1,
   date:"1/7/14",
   time:"3:00 AM",
   unit:"emergency",
   physician:"Cohen",
   charge:300,
   copay:"0",
   insurance:"Medicare",
   inpatient:"TRUE"
}, {
   patient:"Bob",
   patientAge:82,
   visits:1,
   date:"1/7/14",
   time:"8:00 AM",
   unit:"operating room",
   physician:"Adams",
   charge:2300,
   copay:"0",
   insurance:"Medicare",
   inpatient:"TRUE"
}, {
   patient:"Bob",
   patientAge:82,
   visits:1,
   date:"1/7/14",
   time:"11:30 AM",
   unit:"morgue",
   physician:"Doom",
   charge:300,
   copay:"0",
   insurance:"Medicare",
   inpatient:"TRUE"
}, {
   patient:"Carol",
   patientAge:37,
   visits:1,
   date:"1/7/14",
   time:"4:00 AM",
   unit:"emergency",
   physician:"Cohen",
   charge:300,
   copay:"40",
   insurance:"Blue Cross",
   inpatient:"TRUE"
}, {
   patient:"Carol",
   patientAge:37,
   visits:1,
   date:"1/7/14",
   time:"5:30 AM",
   unit:"delivery",
   physician:"Edwards",
   charge:1800,
   copay:"0",
   insurance:"Blue Cross",
   inpatient:"TRUE"
}, {
   patient:"Carol",
   patientAge:37,
   visits:1,
   date:"1/7/14",
   time:"1:00 PM",
   unit:"maternity",
   physician:"Edwards",
   charge:2000,
   copay:"0",
   insurance:"Blue Cross",
   inpatient:"TRUE"
}, {
   patient:"Carol",
   patientAge:37,
   visits:1,
   date:"1/9/14",
   time:"11:00 AM",
   unit:"discharge",
   physician:"Edwards",
   charge:0,
   copay:"0",
   insurance:"Blue Cross",
   inpatient:"TRUE"
}, {
   patient:"Carol",
   patientAge:37,
   visits:2,
   date:"1/13/14",
   time:"9:00 AM",
   unit:"office",
   physician:"Feldman",
   charge:200,
   copay:"20",
   insurance:"Blue Cross",
   inpatient:"FALSE"
}, {
   patient:"Carol",
   patientAge:37,
   visits:3,
   date:"1/27/14",
   time:"9:00 AM",
   unit:"office",
   physician:"Feldman",
   charge:200,
   copay:"20",
   insurance:"Blue Cross",
   inpatient:"FALSE"
}, {
   patient:"Esther",
   patientAge:20,
   visits:1,
   date:"1/7/14",
   time:"3:00 PM",
   unit:"pediatrics",
   physician:"Gupta",
   charge:300,
   copay:"0",
   insurance:"Blue Cross",
   inpatient:"TRUE"
}, {
   patient:"Esther",
   patientAge:20,
   visits:1,
   date:"1/8/14",
   time:"8:00 AM",
   unit:"pediatrics",
   physician:"Gupta",
   charge:300,
   copay:"0",
   insurance:"Blue Cross",
   inpatient:"TRUE"
}, {
   patient:"Esther",
   patientAge:20,
   visits:1,
   date:"1/9/14",
   time:"8:00 AM",
   unit:"pediatrics",
   physician:"Gupta",
   charge:300,
   copay:"0",
   insurance:"Blue Cross",
   inpatient:"TRUE"
}, {
   patient:"Esther",
   patientAge:20,
   visits:2,
   date:"1/13/14",
   time:"11:00 AM",
   unit:"office",
   physician:"Gupta",
   charge:180,
   copay:"20",
   insurance:"Blue Cross",
   inpatient:"FALSE"
}, {
   patient:"Esther",
   patientAge:20,
   visits:3,
   date:"1/27/14",
   time:"11:00 AM",
   unit:"office",
   physician:"Gupta",
   charge:180,
   copay:"20",
   insurance:"Blue Cross",
   inpatient:"FALSE"
}];